-- Copy and paste this into the Supabase SQL Editor to create the necessary table

CREATE TABLE IF NOT EXISTS weather_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id TEXT NOT NULL,
  date DATE NOT NULL,
  avg_temp REAL,
  min_temp REAL,
  max_temp REAL,
  precipitation REAL,
  humidity REAL,
  wind_speed REAL,
  pressure REAL,
  condition TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  
  -- Ensure no duplicate records for the same station on the same date
  UNIQUE(station_id, date)
);

-- Optional: Enable Row Level Security (RLS) and allow public read
ALTER TABLE weather_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
  ON weather_data FOR SELECT 
  USING (true);

-- (For inserting data, we use the backend API with the service/anon key, 
-- but you might need to adjust policies if you strictly block anon inserts.
-- If inserting via anon key in Node, make sure anon has insert access or use the Service Role key.)

CREATE POLICY "Allow public insert" 
  ON weather_data FOR INSERT 
  WITH CHECK (true);

CREATE POLICY "Allow public update" 
  ON weather_data FOR UPDATE 
  USING (true);
